export enum steps {
  GETPHONE="GETPHONE",
  PHONEERROR="PHONEERROR",
  LOADING="LOADING",
  CONFIRMATIONERROR="CONFIRMATIONERROR",
  CONFIRMATIONSUCCESS="CONFIRMATIONSUCCESS",
  CONFIRMATION="CONFIRMATION",
};